AWSTemplateFormatVersion: 2010-09-09
Description: MediEquipStack

Parameters:
  DBPassword:
    Type: String
    NoEcho: true
    Description: The database admin account password

Resources:
  #PUBLIC VPC
  PubVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: PubVPC

  #PUBLIC SUBNETS
  PublicSubnetPubVPC:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref PubVPC
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select
        - 0
        - !GetAZs ''
      Tags:
        - Key: Name
          Value: Public-Subnet-PubVPC
  PublicSubnetPubVPC2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref PubVPC
      CidrBlock: 10.0.2.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select
        - 2
        - !GetAZs ''
      Tags:
        - Key: Name
          Value: Public-Subnet-PubVPC2
  PublicSubnetPubVPC3:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref PubVPC
      CidrBlock: 10.0.3.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select
        - 3
        - !GetAZs ''
      Tags:
        - Key: Name
          Value: Public-Subnet-PubVPC3

  #INTERNET
  InternetGateway:
    Type: AWS::EC2::InternetGateway
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref PubVPC
      InternetGatewayId: !Ref InternetGateway

  #PUBLIC ROUTES
  PublicRouteTablePubVPC:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref PubVPC
  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref PublicRouteTablePubVPC
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
  PubPeeringRoute:
    Type: AWS::EC2::Route
    DependsOn: PubAttachment
    Properties:
      RouteTableId: !Ref PublicRouteTablePubVPC
      DestinationCidrBlock: 192.168.0.0/16
      TransitGatewayId: !Ref myTransitGateway

  #PUBLIC ROUTE ASSOCIATIONS
  PublicRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnetPubVPC
      RouteTableId: !Ref PublicRouteTablePubVPC
  PublicRouteTableAssociation2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnetPubVPC2
      RouteTableId: !Ref PublicRouteTablePubVPC
  PublicRouteTableAssociation3:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnetPubVPC3
      RouteTableId: !Ref PublicRouteTablePubVPC

  #PRIVATE VPC
  PriVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 192.168.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: PriVPC

  #PRIVATE SUBNETS
  PrivateSubnetPriVPC:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref PriVPC
      CidrBlock: 192.168.1.0/24
      MapPublicIpOnLaunch: false
      AvailabilityZone: !Select
        - 0
        - !GetAZs ''
      Tags:
        - Key: Name
          Value: Private-Subnet-PriVPC
  PrivateSubnetPriVPC2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref PriVPC
      CidrBlock: 192.168.2.0/24
      MapPublicIpOnLaunch: false
      AvailabilityZone: !Select
        - 2
        - !GetAZs ''
      Tags:
        - Key: Name
          Value: Private-Subnet-PriVPC2

  #PRIVATE ROUTES
  PrivateRouteTablePriVPC:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref PriVPC
  PriPeeringRoute:
    Type: AWS::EC2::Route
    DependsOn: PriAttachment
    Properties:
      RouteTableId: !Ref PrivateRouteTablePriVPC
      DestinationCidrBlock: 10.0.0.0/16
      TransitGatewayId: !Ref myTransitGateway

  #PRIVATE ROUTE ASSOCIATIONS
  PrivateRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnetPriVPC
      RouteTableId: !Ref PrivateRouteTablePriVPC
  PrivateRouteTableAssociation2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnetPriVPC2
      RouteTableId: !Ref PrivateRouteTablePriVPC

  #Transit Gateway
  myTransitGateway:
    Type: "AWS::EC2::TransitGateway"
    Properties:
      Description: "Transit Gateway for VPCs"
      AutoAcceptSharedAttachments: "disable"
      DefaultRouteTableAssociation: "enable"
      DnsSupport: "enable"
      VpnEcmpSupport: "enable"
      Tags:
      - Key: Name
        Value: My-Transit-Gateway

  PubAttachment:
    Type: AWS::EC2::TransitGatewayAttachment
    Properties:
      SubnetIds:
        - !Ref PublicSubnetPubVPC
        - !Ref PublicSubnetPubVPC2
        - !Ref PublicSubnetPubVPC3
      Tags: 
      - Key: Name
        Value: Pub-Attachment
      TransitGatewayId: !Ref myTransitGateway
      VpcId: !Ref PubVPC

  PriAttachment:
    Type: AWS::EC2::TransitGatewayAttachment
    Properties:
      SubnetIds:
        - !Ref PrivateSubnetPriVPC
        - !Ref PrivateSubnetPriVPC2
      Tags: 
      - Key: Name
        Value: Pri-Attachment
      TransitGatewayId: !Ref myTransitGateway
      VpcId: !Ref PriVPC


  #FILE SERVER [S3]
  FileServerBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: medequip-501-file-server
      PublicAccessBlockConfiguration:
         BlockPublicAcls: false
         BlockPublicPolicy: false
         IgnorePublicAcls: false
         RestrictPublicBuckets: false
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
     Bucket: !Ref FileServerBucket
     PolicyDocument:
      Version: "2012-10-17"
      Statement:
        - Sid: AllowListing
          Effect: Allow
          Principal: "*"
          Action:
            - s3:ListBucket
          Resource: !GetAtt FileServerBucket.Arn

        - Sid: AllowReadAccess
          Effect: Allow
          Principal: "*"
          Action:
            - s3:GetObject
          Resource: !Sub "${FileServerBucket.Arn}/*"


  #DATABASE
  DBSG:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Private Subnet Group
      SubnetIds:
        - !Ref PrivateSubnetPriVPC
        - !Ref PrivateSubnetPriVPC2

  RDSSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: RDS Security Group
      VpcId: !Ref PriVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 10.0.1.0/24
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 10.0.2.0/24
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 10.0.3.0/24

  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 20
      DBInstanceClass: db.t3.micro
      Engine: MySQL
      MasterUsername: admin
      MasterUserPassword: !Ref DBPassword
      DBSubnetGroupName: !Ref DBSG
      VPCSecurityGroups:
        - !GetAtt RDSSG.GroupId

  #security
  BastionSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow RDP, HTTP and SSH
      VpcId: !Ref PubVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3389
          ToPort: 3389
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  #EC2
  BastionInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      ImageId: ami-0fa71268a899c2733
      SubnetId: !Ref PublicSubnetPubVPC
      SecurityGroupIds:
        - !Ref BastionSecurityGroup
      KeyName: vockey

Outputs:
  BastionPublicIp:
    Description: Public IP address of the web server instance
    Value: !GetAtt BastionInstance.PublicIp
  RDSEndpoint:
    Value: !GetAtt RDSInstance.Endpoint.Address
  VpcId:
    Description: Public VPC Id
    Value: !Ref PubVPC
  PublicSubnetPubVPC:
    Description: Subnet 1
    Value: !Ref PublicSubnetPubVPC
  PublicSubnetPubVPC2:
    Description: Subnet 2
    Value: !Ref PublicSubnetPubVPC2
  PublicSubnetPubVPC3:
    Description: Subnet 3
    Value: !Ref PublicSubnetPubVPC3
  BucketName:
    Description: The S3 Bucket Name
    Value: !Ref FileServerBucket
  BucketURL:
    Description: The URL of the S3 Bucket
    Value: !Sub "https://${FileServerBucket}.s3.amazonaws.com/"
  myTransitGatewayId:
    Value: !Ref myTransitGateway
  PubAttachmentId:
    Value: !Ref PubAttachment
  PriAttachmentId:
    Value: !Ref PriAttachment