AWSTemplateFormatVersion: 2010-09-09
Description: MediEquipStack

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: The public VPC Id
  PublicSubnetPubVPC: 
    Type: String
    Description:  public subnet 1
  PublicSubnetPubVPC2: 
    Type: String
    Description:  public subnet 2
  PublicSubnetPubVPC3: 
    Type: String
    Description:  public subnet 3


Resources:
  #security
  CustomerServiceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP, HTTPS and SSH
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
  #EC2

  myLaunchTemplate:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: ami-0953476d60561c955
      InstanceType: t2.micro
      SecurityGroups:
        - !Ref CustomerServiceSecurityGroup

  myASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
        - !Ref PublicSubnetPubVPC
        - !Ref PublicSubnetPubVPC2
        - !Ref PublicSubnetPubVPC3
      LaunchConfigurationName: !Ref myLaunchTemplate
      MaxSize: '3'
      MinSize: '1'
