name: Deploy CF Stack

on:
  workflow_dispatch:
  push:
    branches: ['main']

jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repo
          uses: actions/checkout@v4
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v2
          with: 
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
            aws-region: us-east-1
        - name: List Files
          run: ls -R
          working-directory: ${{ github.workspace }}
        - name: Deploy Main Stack
          run: | 
            aws cloudformation deploy \
              --stack-name MediEquipStack \
              --template-file MediEquipStack.yaml \
              --capabilities CAPABILITY_NAMED_IAM \
              --parameter-overrides DBPassword=${{secrets.DB_PASSWORD}}
        - name: Deploy Web Server Stack
          run: |
            aws cloudformation deploy \
              --stack-name Webserver-asg \
              --template-file Webserver-asg.yaml \
              --capabilities CAPABILITY_NAMED_IAM \
              --parameter-overrides \
              VpcId=$(aws cloudformation describe-stacks --stack-name MediEquipStack --query "Stacks[0].Outputs[?OutputKey=='VpcId'].OutputValue" --output text) \
              PublicSubnetPubVPC=$(aws cloudformation describe-stacks --stack-name MediEquipStack --query "Stacks[0].Outputs [?OutputKey=='PublicSubnetPubVPC'].OutputValue" --output text) \
              PublicSubnetPubVPC2=$(aws cloudformation describe-stacks --stack-name MediEquipStack --query "Stacks[0].Outputs [?OutputKey=='PublicSubnetPubVPC2'].OutputValue" --output text) \
              PublicSubnetPubVPC3=$(aws cloudformation describe-stacks --stack-name MediEquipStack --query "Stacks[0].Outputs [?OutputKey=='PublicSubnetPubVPC3'].OutputValue" --output text) \
              RDSEndpoint=$(aws cloudformation describe-stacks --stack-name MediEquipStack --query "Stacks[0].Outputs[?OutputKey=='RDSEndpoint' ].OutputValue" --output text)
